version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Itca123!
      MYSQL_DATABASE: llanteria
      MYSQL_USER: mjbeta
      MYSQL_PASSWORD: Itca123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  laravel:
    build: ./backend-laravel
    container_name: laravel
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: llanteria
      DB_USERNAME: root 
      DB_PASSWORD: Itca123!
  react:
    build: ./frontend-react
    container_name: react
    ports:
      - "3000:80"

volumes:
  mysql_data: